In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('C:/Users/ASUS/OneDrive/Desktop/jupyter projects/Ml project/Crop_recommendation.csv')

In [3]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
df.isnull()

          N      P      K  temperature  humidity     ph  rainfall  label
0     False  False  False        False     False  False     False  False
1     False  False  False        False     False  False     False  False
2     False  False  False        False     False  False     False  False
3     False  False  False        False     False  False     False  False
4     False  False  False        False     False  False     False  False
...     ...    ...    ...          ...       ...    ...       ...    ...
2195  False  False  False        False     False  False     False  False
2196  False  False  False        False     False  False     False  False
2197  False  False  False        False     False  False     False  False
2198  False  False  False        False     False  False     False  False
2199  False  False  False        False     False  False     False  False

[2200 rows x 8 columns]

In [5]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
df.tail()

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [8]:
 df['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [9]:
x=df.drop('label',axis=1)
y=df['label']

In [10]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
dtypes: float64(4), int64(3)
memory usage: 120.4 KB

In [11]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2200 entries, 0 to 2199
Series name: label
Non-Null Count  Dtype
--------------  -----
2200 non-null   object
dtypes: object(1)
memory usage: 17.3+ KB

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1,test_size=0.3)

In [13]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1540 entries, 625 to 1061
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            1540 non-null   int64
 1   P            1540 non-null   int64
 2   K            1540 non-null   int64
 3   temperature  1540 non-null   float64
 4   humidity     1540 non-null   float64
 5   ph           1540 non-null   float64
 6   rainfall     1540 non-null   float64
dtypes: float64(4), int64(3)
memory usage: 96.2 KB

In [14]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 660 entries, 1276 to 1132
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            660 non-null    int64
 1   P            660 non-null    int64
 2   K            660 non-null    int64
 3   temperature  660 non-null    float64
 4   humidity     660 non-null    float64
 5   ph           660 non-null    float64
 6   rainfall     660 non-null    float64
dtypes: float64(4), int64(3)
memory usage: 41.2 KB

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model=LogisticRegression()
model.fit(x_train,y_train)

C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [17]:
y_pred=model.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score
logistic_reg_acc=accuracy_score(y_test,y_pred)
print("Logistic regression accuracy is "+str(logistic_reg_acc))

Logistic regression accuracy is 0.9651515151515152

In [19]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()
model1.fit(x_train,y_train)

DecisionTreeClassifier()

In [30]:
y_pred1=model1.predict(x_test)

In [31]:
decision_tree_acc=accuracy_score(y_test,y_pred1)
print("Decision tree accuracy is "+str(decision_tree_acc))

Decision tree accuracy is 0.9878787878787879

In [33]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(x_train,y_train)

RandomForestClassifier()

In [34]:
y_pred2=model2.predict(x_test)

In [35]:
random_forest_acc=accuracy_score(y_test,y_pred2)
print("Random forest accuracy is "+str(random_forest_acc))

Random forest accuracy is 0.9954545454545455

In [37]:
import joblib

In [38]:
filename='crop recommender'

In [39]:
joblib.dump(model2,'crop recommender')

['crop recommender']

In [40]:
app=joblib.load('crop recommender')

In [47]:
arr=[[78,42,42,20.130175,81.604873,7.628473,262.717340]]
ans=app.predict(arr)
ans.item()

C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

'rice'